test_that("data loads", {
  skip_on_ci()
  lf <- lsf.str("package:pipaux", pattern = "^pip_[a-z]{3}$")
  lf <- as.character(lf)

  laux <- function(x) {
    y <- gsub("pip_", "", x)
    z <- get(x)

    expect_equal(z("load"), load_aux(y))
  }

  purrr::walk(lf, laux)
})

library(pointblank)
# Generated by pointblank
cpi <- load_aux("cpi", branch = "DEV")

#tbl <- set_tbl(cpi)

test_that("column `country_code` exists", {

  expect_col_exists(
    cpi,
    columns = vars(country_code),
    threshold = 1
  )
})

test_that("column `cpi_year` exists", {

  expect_col_exists(
    cpi,
    columns = vars(cpi_year),
    threshold = 1
  )
})

test_that("column `survey_year` exists", {

  expect_col_exists(
    cpi,
    columns = vars(survey_year),
    threshold = 1
  )
})

test_that("column `cpi` exists", {

  expect_col_exists(
    cpi,
    columns = vars(cpi),
    threshold = 1
  )
})

test_that("column `ccf` exists", {

  expect_col_exists(
    cpi,
    columns = vars(ccf),
    threshold = 1
  )
})

test_that("column `survey_acronym` exists", {

  expect_col_exists(
    cpi,
    columns = vars(survey_acronym),
    threshold = 1
  )
})

test_that("column `change_cpi2011` exists", {

  expect_col_exists(
    cpi,
    columns = vars(change_cpi2011),
    threshold = 1
  )
})

test_that("column `cpi_domain` exists", {

  expect_col_exists(
    cpi,
    columns = vars(cpi_domain),
    threshold = 1
  )
})

test_that("column `cpi_domain_value` exists", {

  expect_col_exists(
    cpi,
    columns = vars(cpi_domain_value),
    threshold = 1
  )
})

test_that("column `cpi2017_unadj` exists", {

  expect_col_exists(
    cpi,
    columns = vars(cpi2017_unadj),
    threshold = 1
  )
})

test_that("column `cpi2011_unadj` exists", {

  expect_col_exists(
    cpi,
    columns = vars(cpi2011_unadj),
    threshold = 1
  )
})

test_that("column `cpi2011` exists", {

  expect_col_exists(
    cpi,
    columns = vars(cpi2011),
    threshold = 1
  )
})

test_that("column `cpi2017` exists", {

  expect_col_exists(
    cpi,
    columns = vars(cpi2017),
    threshold = 1
  )
})

test_that("column `cpi2011_SM22` exists", {

  expect_col_exists(
    cpi,
    columns = vars(cpi2011_SM22),
    threshold = 1
  )
})

test_that("column `cpi2017_SM22` exists", {

  expect_col_exists(
    cpi,
    columns = vars(cpi2017_SM22),
    threshold = 1
  )
})

test_that("column `cpi2005` exists", {

  expect_col_exists(
    cpi,
    columns = vars(cpi2005),
    threshold = 1
  )
})

test_that("column `cpi_data_level` exists", {

  expect_col_exists(
    cpi,
    columns = vars(cpi_data_level),
    threshold = 1
  )
})

test_that("column `cpi_id` exists", {

  expect_col_exists(
    cpi,
    columns = vars(cpi_id),
    threshold = 1
  )
})

test_that("column `country_code` is of type: character", {

  expect_col_is_character(
    cpi,
    columns = vars(country_code),
    threshold = 1
  )
})

test_that("column `survey_acronym` is of type: character", {

  expect_col_is_character(
    cpi,
    columns = vars(survey_acronym),
    threshold = 1
  )
})

test_that("column `cpi_domain` is of type: character", {

  expect_col_is_character(
    cpi,
    columns = vars(cpi_domain),
    threshold = 1
  )
})

test_that("column `cpi_data_level` is of type: character", {

  expect_col_is_character(
    cpi,
    columns = vars(cpi_data_level),
    threshold = 1
  )
})

test_that("column `cpi_id` is of type: character", {

  expect_col_is_character(
    cpi,
    columns = vars(cpi_id),
    threshold = 1
  )
})

test_that("column `survey_year` is of type: numeric", {

  expect_col_is_numeric(
    cpi,
    columns = vars(survey_year),
    threshold = 1
  )
})

test_that("column `cpi` is of type: numeric", {

  expect_col_is_numeric(
    cpi,
    columns = vars(cpi),
    threshold = 1
  )
})

test_that("column `ccf` is of type: numeric", {

  expect_col_is_numeric(
    cpi,
    columns = vars(ccf),
    threshold = 1
  )
})

test_that("column `change_cpi2011` is of type: numeric", {

  expect_col_is_numeric(
    cpi,
    columns = vars(change_cpi2011),
    threshold = 1
  )
})

test_that("column `cpi_domain_value` is of type: numeric", {

  expect_col_is_numeric(
    cpi,
    columns = vars(cpi_domain_value),
    threshold = 1
  )
})

test_that("column `cpi2017_unadj` is of type: numeric", {

  expect_col_is_numeric(
    cpi,
    columns = vars(cpi2017_unadj),
    threshold = 1
  )
})

test_that("column `cpi2011_unadj` is of type: numeric", {

  expect_col_is_numeric(
    cpi,
    columns = vars(cpi2011_unadj),
    threshold = 1
  )
})

test_that("column `cpi2011` is of type: numeric", {

  expect_col_is_numeric(
    cpi,
    columns = vars(cpi2011),
    threshold = 1
  )
})

test_that("column `cpi2017` is of type: numeric", {

  expect_col_is_numeric(
    cpi,
    columns = vars(cpi2017),
    threshold = 1
  )
})

test_that("column `cpi2011_SM22` is of type: numeric", {

  expect_col_is_numeric(
    cpi,
    columns = vars(cpi2011_SM22),
    threshold = 1
  )
})

test_that("column `cpi2017_SM22` is of type: numeric", {

  expect_col_is_numeric(
    cpi,
    columns = vars(cpi2017_SM22),
    threshold = 1
  )
})

test_that("column `cpi_year` is of type: integer", {

  expect_col_is_integer(
    cpi,
    columns = vars(cpi_year),
    threshold = 1
  )
})

test_that("column `cpi2005` is of type: logical", {

  expect_col_is_logical(
    cpi,
    columns = vars(cpi2005),
    threshold = 1
  )
})

test_that("all values in `country_code` should not be NULL", {

  expect_col_vals_not_null(
    cpi,
    columns = vars(country_code),
    threshold = 1
  )
})

test_that("all values in `cpi_year` should not be NULL", {

  expect_col_vals_not_null(
    cpi,
    columns = vars(cpi_year),
    threshold = 1
  )
})

test_that("all values in `survey_year` should not be NULL", {

  expect_col_vals_not_null(
    cpi,
    columns = vars(survey_year),
    threshold = 1
  )
})

test_that("all values in `cpi` should not be NULL", {

  expect_col_vals_not_null(
    cpi,
    columns = vars(cpi),
    threshold = 1
  )
})

test_that("all values in `survey_acronym` should not be NULL", {

  expect_col_vals_not_null(
    cpi,
    columns = vars(survey_acronym),
    threshold = 1
  )
})

test_that("all values in `cpi_data_level` should not be NULL", {

  expect_col_vals_not_null(
    cpi,
    columns = vars(cpi_data_level),
    threshold = 1
  )
})

test_that("values in `country_code` should match the regular expression: `^[A-Z]{3}$`", {

  expect_col_vals_regex(
    cpi,
    columns = vars(country_code),
    regex = "^[A-Z]{3}$",
    threshold = 1
  )
})

test_that("entirely distinct rows across `country_code, cpi_year, survey_acronym, cpi_data_level`", {

  expect_rows_distinct(
    cpi,
    columns = vars(country_code, cpi_year, survey_acronym, cpi_data_level),
    threshold = 1
  )
})

test_that("values in `cpi_domain` should be in the set of `National`, `Urban/Rural`", {

  expect_col_vals_in_set(
    cpi,
    columns = vars(cpi_domain),
    set = c("National", "Urban/Rural"),
    threshold = 1
  )
})

test_that("values in `cpi_data_level` should be in the set of `national`, `rural`, `urban`", {

  expect_col_vals_in_set(
    cpi,
    columns = vars(cpi_data_level),
    set = c("national", "rural", "urban"),
    threshold = 1
  )
})
################################################################################

# checking gdm raw data
# Generated by pointblank
gdm <- load_aux("gdm", branch = "DEV")

test_that("column `survey_id` exists", {

  expect_col_exists(
    gdm,
    columns = vars(survey_id),
    threshold = 1
  )
})

test_that("column `country_code` exists", {

  expect_col_exists(
    gdm,
    columns = vars(country_code),
    threshold = 1
  )
})

test_that("column `surveyid_year` exists", {

  expect_col_exists(
    gdm,
    columns = vars(surveyid_year),
    threshold = 1
  )
})

test_that("column `survey_year` exists", {

  expect_col_exists(
    gdm,
    columns = vars(survey_year),
    threshold = 1
  )
})

test_that("column `welfare_type` exists", {

  expect_col_exists(
    gdm,
    columns = vars(welfare_type),
    threshold = 1
  )
})

test_that("column `survey_mean_lcu` exists", {

  expect_col_exists(
    gdm,
    columns = vars(survey_mean_lcu),
    threshold = 1
  )
})

test_that("column `distribution_type` exists", {

  expect_col_exists(
    gdm,
    columns = vars(distribution_type),
    threshold = 1
  )
})

test_that("column `gd_type` exists", {

  expect_col_exists(
    gdm,
    columns = vars(gd_type),
    threshold = 1
  )
})

test_that("column `pop_data_level` exists", {

  expect_col_exists(
    gdm,
    columns = vars(pop_data_level),
    threshold = 1
  )
})

test_that("column `pcn_source_file` exists", {

  expect_col_exists(
    gdm,
    columns = vars(pcn_source_file),
    threshold = 1
  )
})

test_that("column `pcn_survey_id` exists", {

  expect_col_exists(
    gdm,
    columns = vars(pcn_survey_id),
    threshold = 1
  )
})

test_that("column `survey_id` is of type: character", {

  expect_col_is_character(
    gdm,
    columns = vars(survey_id),
    threshold = 1
  )
})

test_that("column `country_code` is of type: character", {

  expect_col_is_character(
    gdm,
    columns = vars(country_code),
    threshold = 1
  )
})

test_that("column `welfare_type` is of type: character", {

  expect_col_is_character(
    gdm,
    columns = vars(welfare_type),
    threshold = 1
  )
})

test_that("column `distribution_type` is of type: character", {

  expect_col_is_character(
    gdm,
    columns = vars(distribution_type),
    threshold = 1
  )
})

test_that("column `gd_type` is of type: character", {

  expect_col_is_character(
    gdm,
    columns = vars(gd_type),
    threshold = 1
  )
})

test_that("column `pop_data_level` is of type: character", {

  expect_col_is_character(
    gdm,
    columns = vars(pop_data_level),
    threshold = 1
  )
})

test_that("column `pcn_source_file` is of type: character", {

  expect_col_is_character(
    gdm,
    columns = vars(pcn_source_file),
    threshold = 1
  )
})

test_that("column `pcn_survey_id` is of type: character", {

  expect_col_is_character(
    gdm,
    columns = vars(pcn_survey_id),
    threshold = 1
  )
})

test_that("column `survey_year` is of type: numeric", {

  expect_col_is_numeric(
    gdm,
    columns = vars(survey_year),
    threshold = 1
  )
})

test_that("column `survey_mean_lcu` is of type: numeric", {

  expect_col_is_numeric(
    gdm,
    columns = vars(survey_mean_lcu),
    threshold = 1
  )
})

test_that("column `surveyid_year` is of type: integer", {

  expect_col_is_integer(
    gdm,
    columns = vars(surveyid_year),
    threshold = 1
  )
})

test_that("all values in `survey_id` should not be NULL", {

  expect_col_vals_not_null(
    gdm,
    columns = vars(survey_id),
    threshold = 1
  )
})

test_that("all values in `country_code` should not be NULL", {

  expect_col_vals_not_null(
    gdm,
    columns = vars(country_code),
    threshold = 1
  )
})

test_that("all values in `pop_data_level` should not be NULL", {

  expect_col_vals_not_null(
    gdm,
    columns = vars(pop_data_level),
    threshold = 1
  )
})

test_that("values in `country_code` should match the regular expression: `^[A-Z]{3}$`", {

  expect_col_vals_regex(
    gdm,
    columns = vars(country_code),
    regex = "^[A-Z]{3}$",
    threshold = 1
  )
})

test_that("entirely distinct rows across `survey_id, country_code, pop_data_level`", {

  expect_rows_distinct(
    gdm,
    columns = vars(survey_id, country_code, pop_data_level),
    threshold = 1
  )
})

test_that("values in `welfare_type` should be in the set of `consumption`, `income`", {

  expect_col_vals_in_set(
    gdm,
    columns = vars(welfare_type),
    set = c("consumption", "income"),
    threshold = 1
  )
})

test_that("values in `distribution_type` should be in the set of `aggregate`, `group`", {

  expect_col_vals_in_set(
    gdm,
    columns = vars(distribution_type),
    set = c("aggregate", "group"),
    threshold = 1
  )
})

################################################################################

# checking gdp raw data
# Generated by pointblank
gdp <- load_aux("gdp", branch = "DEV")

test_that("column `country_code` exists", {

  expect_col_exists(
    gdp,
    columns = vars(country_code),
    threshold = 1
  )
})

test_that("column `year` exists", {

  expect_col_exists(
    gdp,
    columns = vars(year),
    threshold = 1
  )
})

test_that("column `gdp` exists", {

  expect_col_exists(
    gdp,
    columns = vars(gdp),
    threshold = 1
  )
})

test_that("column `gdp_data_level` exists", {

  expect_col_exists(
    gdp,
    columns = vars(gdp_data_level),
    threshold = 1
  )
})

test_that("column `gdp_domain` exists", {

  expect_col_exists(
    gdp,
    columns = vars(gdp_domain),
    threshold = 1
  )
})

test_that("column `country_code` is of type: character", {

  expect_col_is_character(
    gdp,
    columns = vars(country_code),
    threshold = 1
  )
})

test_that("column `gdp_data_level` is of type: character", {

  expect_col_is_character(
    gdp,
    columns = vars(gdp_data_level),
    threshold = 1
  )
})

test_that("column `gdp_domain` is of type: character", {

  expect_col_is_character(
    gdp,
    columns = vars(gdp_domain),
    threshold = 1
  )
})

test_that("column `year` is of type: numeric", {

  expect_col_is_numeric(
    gdp,
    columns = vars(year),
    threshold = 1
  )
})

test_that("column `gdp` is of type: numeric", {

  expect_col_is_numeric(
    gdp,
    columns = vars(gdp),
    threshold = 1
  )
})

test_that("all values in `country_code` should not be NULL", {

  expect_col_vals_not_null(
    gdp,
    columns = vars(country_code),
    threshold = 1
  )
})

test_that("all values in `year` should not be NULL", {

  expect_col_vals_not_null(
    gdp,
    columns = vars(year),
    threshold = 1
  )
})

test_that("all values in `gdp_data_level` should not be NULL", {

  expect_col_vals_not_null(
    gdp,
    columns = vars(gdp_data_level),
    threshold = 1
  )
})

test_that("values in `country_code` should match the regular expression: `^[A-Z]{3}$`", {

  expect_col_vals_regex(
    gdp,
    columns = vars(country_code),
    regex = "^[A-Z]{3}$",
    threshold = 1
  )
})

test_that("entirely distinct rows across `country_code, year, gdp_data_level`", {

  expect_rows_distinct(
    gdp,
    columns = vars(country_code, year, gdp_data_level),
    threshold = 1
  )
})

test_that("values in `gdp_domain` should be in the set of `national`, `urban/rural`", {

  expect_col_vals_in_set(
    gdp,
    columns = vars(gdp_domain),
    set = c("national", "urban/rural"),
    threshold = 1
  )
})

test_that("values in `gdp_data_level` should be in the set of `national`, `rural`, `urban`", {

  expect_col_vals_in_set(
    gdp,
    columns = vars(gdp_data_level),
    set = c("national", "rural", "urban"),
    threshold = 1
  )
})
################################################################################

# checking npl raw data
# Generated by pointblank
npl <- load_aux("npl", branch = "DEV")

test_that("column `country_code` exists", {

  expect_col_exists(
    npl,
    columns = vars(country_code),
    threshold = 1
  )
})

test_that("column `reporting_year` exists", {

  expect_col_exists(
    npl,
    columns = vars(reporting_year),
    threshold = 1
  )
})

test_that("column `nat_headcount` exists", {

  expect_col_exists(
    npl,
    columns = vars(nat_headcount),
    threshold = 1
  )
})

test_that("column `comparability` exists", {

  expect_col_exists(
    npl,
    columns = vars(comparability),
    threshold = 1
  )
})

test_that("column `footnote` exists", {

  expect_col_exists(
    npl,
    columns = vars(footnote),
    threshold = 1
  )
})

test_that("column `country_code` is of type: character", {

  expect_col_is_character(
    npl,
    columns = vars(country_code),
    threshold = 1
  )
})

test_that("column `footnote` is of type: character", {

  expect_col_is_character(
    npl,
    columns = vars(footnote),
    threshold = 1
  )
})

test_that("column `reporting_year` is of type: numeric", {

  expect_col_is_numeric(
    npl,
    columns = vars(reporting_year),
    threshold = 1
  )
})

test_that("column `nat_headcount` is of type: numeric", {

  expect_col_is_numeric(
    npl,
    columns = vars(nat_headcount),
    threshold = 1
  )
})

test_that("column `comparability` is of type: numeric", {

  expect_col_is_numeric(
    npl,
    columns = vars(comparability),
    threshold = 1
  )
})

test_that("all values in `country_code` should not be NULL", {

  expect_col_vals_not_null(
    npl,
    columns = vars(country_code),
    threshold = 1
  )
})

test_that("all values in `reporting_year` should not be NULL", {

  expect_col_vals_not_null(
    npl,
    columns = vars(reporting_year),
    threshold = 1
  )
})

test_that("values in `country_code` should match the regular expression: `^[A-Z]{3}$`", {

  expect_col_vals_regex(
    npl,
    columns = vars(country_code),
    regex = "^[A-Z]{3}$",
    threshold = 1
  )
})

test_that("entirely distinct rows across `country_code, reporting_year`", {

  expect_rows_distinct(
    npl,
    columns = vars(country_code, reporting_year),
    threshold = 1
  )
})
################################################################################

# checking pce raw data
# Generated by pointblank

pce <- load_aux("pce", branch = "DEV")

test_that("column `country_code` exists", {

  expect_col_exists(
    pce,
    columns = vars(country_code),
    threshold = 1
  )
})

test_that("column `year` exists", {

  expect_col_exists(
    pce,
    columns = vars(year),
    threshold = 1
  )
})

test_that("column `pce` exists", {

  expect_col_exists(
    pce,
    columns = vars(pce),
    threshold = 1
  )
})

test_that("column `pce_data_level` exists", {

  expect_col_exists(
    pce,
    columns = vars(pce_data_level),
    threshold = 1
  )
})

test_that("column `pce_domain` exists", {

  expect_col_exists(
    pce,
    columns = vars(pce_domain),
    threshold = 1
  )
})

test_that("column `country_code` is of type: character", {

  expect_col_is_character(
    pce,
    columns = vars(country_code),
    threshold = 1
  )
})

test_that("column `pce_data_level` is of type: character", {

  expect_col_is_character(
    pce,
    columns = vars(pce_data_level),
    threshold = 1
  )
})

test_that("column `pce_domain` is of type: character", {

  expect_col_is_character(
    pce,
    columns = vars(pce_domain),
    threshold = 1
  )
})

test_that("column `year` is of type: numeric", {

  expect_col_is_numeric(
    pce,
    columns = vars(year),
    threshold = 1
  )
})

test_that("column `pce` is of type: numeric", {

  expect_col_is_numeric(
    pce,
    columns = vars(pce),
    threshold = 1
  )
})

test_that("all values in `country_code` should not be NULL", {

  expect_col_vals_not_null(
    pce,
    columns = vars(country_code),
    threshold = 1
  )
})

test_that("all values in `year` should not be NULL", {

  expect_col_vals_not_null(
    pce,
    columns = vars(year),
    threshold = 1
  )
})

test_that("all values in `pce_data_level` should not be NULL", {

  expect_col_vals_not_null(
    pce,
    columns = vars(pce_data_level),
    threshold = 1
  )
})

test_that("values in `country_code` should match the regular expression: `^[A-Z]{3}$`", {

  expect_col_vals_regex(
    pce,
    columns = vars(country_code),
    regex = "^[A-Z]{3}$",
    threshold = 1
  )
})

test_that("entirely distinct rows across `country_code, year, pce_data_level`", {

  expect_rows_distinct(
    pce,
    columns = vars(country_code, year, pce_data_level),
    threshold = 1
  )
})

test_that("values in `pce_domain` should be in the set of `national`, `urban/rural`", {

  expect_col_vals_in_set(
    pce,
    columns = vars(pce_domain),
    set = c("national", "urban/rural"),
    threshold = 1
  )
})

test_that("values in `pce_data_level` should be in the set of `national`, `rural`, `urban`", {

  expect_col_vals_in_set(
    pce,
    columns = vars(pce_data_level),
    set = c("national", "rural", "urban"),
    threshold = 1
  )
})

################################################################################

# checking pfw raw data
# Generated by pointblank

pfw <- load_aux("pfw", branch = "DEV")

test_that("column `wb_region_code` exists", {

  expect_col_exists(
    pfw,
    columns = vars(wb_region_code),
    threshold = 1
  )
})

test_that("column `country_code` exists", {

  expect_col_exists(
    pfw,
    columns = vars(country_code),
    threshold = 1
  )
})

test_that("column `pcn_region_code` exists", {

  expect_col_exists(
    pfw,
    columns = vars(pcn_region_code),
    threshold = 1
  )
})

test_that("column `ctryname` exists", {

  expect_col_exists(
    pfw,
    columns = vars(ctryname),
    threshold = 1
  )
})

test_that("column `survey_acronym` exists", {

  expect_col_exists(
    pfw,
    columns = vars(survey_acronym),
    threshold = 1
  )
})

test_that("column `link` exists", {

  expect_col_exists(
    pfw,
    columns = vars(link),
    threshold = 1
  )
})

test_that("column `altname` exists", {

  expect_col_exists(
    pfw,
    columns = vars(altname),
    threshold = 1
  )
})

test_that("column `survey_time` exists", {

  expect_col_exists(
    pfw,
    columns = vars(survey_time),
    threshold = 1
  )
})

test_that("column `year` exists", {

  expect_col_exists(
    pfw,
    columns = vars(year),
    threshold = 1
  )
})

test_that("column `surveyid_year` exists", {

  expect_col_exists(
    pfw,
    columns = vars(surveyid_year),
    threshold = 1
  )
})

test_that("column `timewp` exists", {

  expect_col_exists(
    pfw,
    columns = vars(timewp),
    threshold = 1
  )
})

test_that("column `fieldwork` exists", {

  expect_col_exists(
    pfw,
    columns = vars(fieldwork),
    threshold = 1
  )
})

test_that("column `wbint_link` exists", {

  expect_col_exists(
    pfw,
    columns = vars(wbint_link),
    threshold = 1
  )
})

test_that("column `wbext_link` exists", {

  expect_col_exists(
    pfw,
    columns = vars(wbext_link),
    threshold = 1
  )
})

test_that("column `alt_link` exists", {

  expect_col_exists(
    pfw,
    columns = vars(alt_link),
    threshold = 1
  )
})

test_that("column `pip_meta` exists", {

  expect_col_exists(
    pfw,
    columns = vars(pip_meta),
    threshold = 1
  )
})

test_that("column `surv_title` exists", {

  expect_col_exists(
    pfw,
    columns = vars(surv_title),
    threshold = 1
  )
})

test_that("column `surv_producer` exists", {

  expect_col_exists(
    pfw,
    columns = vars(surv_producer),
    threshold = 1
  )
})

test_that("column `survey_coverage` exists", {

  expect_col_exists(
    pfw,
    columns = vars(survey_coverage),
    threshold = 1
  )
})

test_that("column `welfare_type` exists", {

  expect_col_exists(
    pfw,
    columns = vars(welfare_type),
    threshold = 1
  )
})

test_that("column `use_imputed` exists", {

  expect_col_exists(
    pfw,
    columns = vars(use_imputed),
    threshold = 1
  )
})

test_that("column `use_microdata` exists", {

  expect_col_exists(
    pfw,
    columns = vars(use_microdata),
    threshold = 1
  )
})

test_that("column `use_bin` exists", {

  expect_col_exists(
    pfw,
    columns = vars(use_bin),
    threshold = 1
  )
})

test_that("column `use_groupdata` exists", {

  expect_col_exists(
    pfw,
    columns = vars(use_groupdata),
    threshold = 1
  )
})

test_that("column `reporting_year` exists", {

  expect_col_exists(
    pfw,
    columns = vars(reporting_year),
    threshold = 1
  )
})

test_that("column `survey_comparability` exists", {

  expect_col_exists(
    pfw,
    columns = vars(survey_comparability),
    threshold = 1
  )
})

test_that("column `comp_note` exists", {

  expect_col_exists(
    pfw,
    columns = vars(comp_note),
    threshold = 1
  )
})

test_that("column `preferable` exists", {

  expect_col_exists(
    pfw,
    columns = vars(preferable),
    threshold = 1
  )
})

test_that("column `display_cp` exists", {

  expect_col_exists(
    pfw,
    columns = vars(display_cp),
    threshold = 1
  )
})

test_that("column `fieldwork_range` exists", {

  expect_col_exists(
    pfw,
    columns = vars(fieldwork_range),
    threshold = 1
  )
})

test_that("column `survey_year` exists", {

  expect_col_exists(
    pfw,
    columns = vars(survey_year),
    threshold = 1
  )
})

test_that("column `newref` exists", {

  expect_col_exists(
    pfw,
    columns = vars(newref),
    threshold = 1
  )
})

test_that("column `ref_year_des` exists", {

  expect_col_exists(
    pfw,
    columns = vars(ref_year_des),
    threshold = 1
  )
})

test_that("column `wf_baseprice` exists", {

  expect_col_exists(
    pfw,
    columns = vars(wf_baseprice),
    threshold = 1
  )
})

test_that("column `wf_baseprice_note` exists", {

  expect_col_exists(
    pfw,
    columns = vars(wf_baseprice_note),
    threshold = 1
  )
})

test_that("column `wf_baseprice_des` exists", {

  expect_col_exists(
    pfw,
    columns = vars(wf_baseprice_des),
    threshold = 1
  )
})

test_that("column `wf_spatial_des` exists", {

  expect_col_exists(
    pfw,
    columns = vars(wf_spatial_des),
    threshold = 1
  )
})

test_that("column `wf_spatial_var` exists", {

  expect_col_exists(
    pfw,
    columns = vars(wf_spatial_var),
    threshold = 1
  )
})

test_that("column `cpi_replication` exists", {

  expect_col_exists(
    pfw,
    columns = vars(cpi_replication),
    threshold = 1
  )
})

test_that("column `cpi_domain` exists", {

  expect_col_exists(
    pfw,
    columns = vars(cpi_domain),
    threshold = 1
  )
})

test_that("column `cpi_domain_var` exists", {

  expect_col_exists(
    pfw,
    columns = vars(cpi_domain_var),
    threshold = 1
  )
})

test_that("column `wf_currency_des` exists", {

  expect_col_exists(
    pfw,
    columns = vars(wf_currency_des),
    threshold = 1
  )
})

test_that("column `ppp_replication` exists", {

  expect_col_exists(
    pfw,
    columns = vars(ppp_replication),
    threshold = 1
  )
})

test_that("column `ppp_domain` exists", {

  expect_col_exists(
    pfw,
    columns = vars(ppp_domain),
    threshold = 1
  )
})

test_that("column `ppp_domain_var` exists", {

  expect_col_exists(
    pfw,
    columns = vars(ppp_domain_var),
    threshold = 1
  )
})

test_that("column `wf_add_temp_des` exists", {

  expect_col_exists(
    pfw,
    columns = vars(wf_add_temp_des),
    threshold = 1
  )
})

test_that("column `wf_add_temp_var` exists", {

  expect_col_exists(
    pfw,
    columns = vars(wf_add_temp_var),
    threshold = 1
  )
})

test_that("column `wf_add_spatial_des` exists", {

  expect_col_exists(
    pfw,
    columns = vars(wf_add_spatial_des),
    threshold = 1
  )
})

test_that("column `wf_add_spatial_var` exists", {

  expect_col_exists(
    pfw,
    columns = vars(wf_add_spatial_var),
    threshold = 1
  )
})

test_that("column `tosplit` exists", {

  expect_col_exists(
    pfw,
    columns = vars(tosplit),
    threshold = 1
  )
})

test_that("column `tosplit_var` exists", {

  expect_col_exists(
    pfw,
    columns = vars(tosplit_var),
    threshold = 1
  )
})

test_that("column `inpovcal` exists", {

  expect_col_exists(
    pfw,
    columns = vars(inpovcal),
    threshold = 1
  )
})

test_that("column `oth_welfare1_type` exists", {

  expect_col_exists(
    pfw,
    columns = vars(oth_welfare1_type),
    threshold = 1
  )
})

test_that("column `oth_welfare1_var` exists", {

  expect_col_exists(
    pfw,
    columns = vars(oth_welfare1_var),
    threshold = 1
  )
})

test_that("column `gdp_domain` exists", {

  expect_col_exists(
    pfw,
    columns = vars(gdp_domain),
    threshold = 1
  )
})

test_that("column `pce_domain` exists", {

  expect_col_exists(
    pfw,
    columns = vars(pce_domain),
    threshold = 1
  )
})

test_that("column `pop_domain` exists", {

  expect_col_exists(
    pfw,
    columns = vars(pop_domain),
    threshold = 1
  )
})

test_that("column `Note` exists", {

  expect_col_exists(
    pfw,
    columns = vars(Note),
    threshold = 1
  )
})

test_that("column `pfw_id` exists", {

  expect_col_exists(
    pfw,
    columns = vars(pfw_id),
    threshold = 1
  )
})

test_that("column `wb_region_code` is of type: character", {

  expect_col_is_character(
    pfw,
    columns = vars(wb_region_code),
    threshold = 1
  )
})

test_that("column `country_code` is of type: character", {

  expect_col_is_character(
    pfw,
    columns = vars(country_code),
    threshold = 1
  )
})

test_that("column `pcn_region_code` is of type: character", {

  expect_col_is_character(
    pfw,
    columns = vars(pcn_region_code),
    threshold = 1
  )
})

test_that("column `ctryname` is of type: character", {

  expect_col_is_character(
    pfw,
    columns = vars(ctryname),
    threshold = 1
  )
})

test_that("column `survey_acronym` is of type: character", {

  expect_col_is_character(
    pfw,
    columns = vars(survey_acronym),
    threshold = 1
  )
})

test_that("column `link` is of type: character", {

  expect_col_is_character(
    pfw,
    columns = vars(link),
    threshold = 1
  )
})

test_that("column `altname` is of type: character", {

  expect_col_is_character(
    pfw,
    columns = vars(altname),
    threshold = 1
  )
})

test_that("column `survey_time` is of type: character", {

  expect_col_is_character(
    pfw,
    columns = vars(survey_time),
    threshold = 1
  )
})

test_that("column `surv_title` is of type: character", {

  expect_col_is_character(
    pfw,
    columns = vars(surv_title),
    threshold = 1
  )
})

test_that("column `surv_producer` is of type: character", {

  expect_col_is_character(
    pfw,
    columns = vars(surv_producer),
    threshold = 1
  )
})

test_that("column `survey_coverage` is of type: character", {

  expect_col_is_character(
    pfw,
    columns = vars(survey_coverage),
    threshold = 1
  )
})

test_that("column `welfare_type` is of type: character", {

  expect_col_is_character(
    pfw,
    columns = vars(welfare_type),
    threshold = 1
  )
})

test_that("column `comp_note` is of type: character", {

  expect_col_is_character(
    pfw,
    columns = vars(comp_note),
    threshold = 1
  )
})

test_that("column `preferable` is of type: character", {

  expect_col_is_character(
    pfw,
    columns = vars(preferable),
    threshold = 1
  )
})

test_that("column `fieldwork_range` is of type: character", {

  expect_col_is_character(
    pfw,
    columns = vars(fieldwork_range),
    threshold = 1
  )
})

test_that("column `wf_baseprice` is of type: character", {

  expect_col_is_character(
    pfw,
    columns = vars(wf_baseprice),
    threshold = 1
  )
})

test_that("column `newref` is of type: character", {

  expect_col_is_character(
    pfw,
    columns = vars(newref),
    threshold = 1
  )
})

test_that("column `wf_baseprice_note` is of type: character", {

  expect_col_is_character(
    pfw,
    columns = vars(wf_baseprice_note),
    threshold = 1
  )
})

test_that("column `wf_spatial_var` is of type: character", {

  expect_col_is_character(
    pfw,
    columns = vars(wf_spatial_var),
    threshold = 1
  )
})

test_that("column `cpi_domain_var` is of type: character", {

  expect_col_is_character(
    pfw,
    columns = vars(cpi_domain_var),
    threshold = 1
  )
})

test_that("column `ppp_domain_var` is of type: character", {

  expect_col_is_character(
    pfw,
    columns = vars(ppp_domain_var),
    threshold = 1
  )
})

test_that("column `tosplit_var` is of type: character", {

  expect_col_is_character(
    pfw,
    columns = vars(tosplit_var),
    threshold = 1
  )
})

test_that("column `oth_welfare1_type` is of type: character", {

  expect_col_is_character(
    pfw,
    columns = vars(oth_welfare1_type),
    threshold = 1
  )
})

test_that("column `oth_welfare1_var` is of type: character", {

  expect_col_is_character(
    pfw,
    columns = vars(oth_welfare1_var),
    threshold = 1
  )
})

test_that("column `Note` is of type: character", {

  expect_col_is_character(
    pfw,
    columns = vars(Note),
    threshold = 1
  )
})

test_that("column `pfw_id` is of type: character", {

  expect_col_is_character(
    pfw,
    columns = vars(pfw_id),
    threshold = 1
  )
})

test_that("column `surveyid_year` is of type: integer", {

  expect_col_is_integer(
    pfw,
    columns = vars(surveyid_year),
    threshold = 1
  )
})

test_that("column `year` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(year),
    threshold = 1
  )
})

test_that("column `timewp` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(timewp),
    threshold = 1
  )
})

test_that("column `fieldwork` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(fieldwork),
    threshold = 1
  )
})

test_that("column `wbint_link` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(wbint_link),
    threshold = 1
  )
})

test_that("column `wbext_link` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(wbext_link),
    threshold = 1
  )
})

test_that("column `alt_link` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(alt_link),
    threshold = 1
  )
})

test_that("column `pip_meta` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(pip_meta),
    threshold = 1
  )
})

test_that("column `use_imputed` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(use_imputed),
    threshold = 1
  )
})

test_that("column `use_microdata` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(use_microdata),
    threshold = 1
  )
})

test_that("column `use_bin` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(use_bin),
    threshold = 1
  )
})

test_that("column `use_groupdata` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(use_groupdata),
    threshold = 1
  )
})

test_that("column `reporting_year` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(reporting_year),
    threshold = 1
  )
})

test_that("column `survey_comparability` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(survey_comparability),
    threshold = 1
  )
})

test_that("column `display_cp` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(display_cp),
    threshold = 1
  )
})

test_that("column `survey_year` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(survey_year),
    threshold = 1
  )
})

test_that("column `ref_year_des` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(ref_year_des),
    threshold = 1
  )
})

test_that("column `wf_baseprice_des` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(wf_baseprice_des),
    threshold = 1
  )
})

test_that("column `wf_spatial_des` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(wf_spatial_des),
    threshold = 1
  )
})

test_that("column `cpi_replication` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(cpi_replication),
    threshold = 1
  )
})

test_that("column `cpi_domain` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(cpi_domain),
    threshold = 1
  )
})

test_that("column `wf_currency_des` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(wf_currency_des),
    threshold = 1
  )
})

test_that("column `ppp_replication` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(ppp_replication),
    threshold = 1
  )
})

test_that("column `ppp_domain` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(ppp_domain),
    threshold = 1
  )
})

test_that("column `wf_add_temp_des` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(wf_add_temp_des),
    threshold = 1
  )
})

test_that("column `wf_add_temp_var` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(wf_add_temp_var),
    threshold = 1
  )
})

test_that("column `wf_add_spatial_des` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(wf_add_spatial_des),
    threshold = 1
  )
})

test_that("column `wf_add_spatial_var` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(wf_add_spatial_var),
    threshold = 1
  )
})

test_that("column `tosplit` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(tosplit),
    threshold = 1
  )
})

test_that("column `inpovcal` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(inpovcal),
    threshold = 1
  )
})

test_that("column `gdp_domain` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(gdp_domain),
    threshold = 1
  )
})

test_that("column `pce_domain` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(pce_domain),
    threshold = 1
  )
})

test_that("column `pop_domain` is of type: numeric", {

  expect_col_is_numeric(
    pfw,
    columns = vars(pop_domain),
    threshold = 1
  )
})

test_that("all values in `country_code` should not be NULL", {

  expect_col_vals_not_null(
    pfw,
    columns = vars(country_code),
    threshold = 1
  )
})

test_that("all values in `year` should not be NULL", {

  expect_col_vals_not_null(
    pfw,
    columns = vars(year),
    threshold = 1
  )
})

test_that("all values in `survey_acronym` should not be NULL", {

  expect_col_vals_not_null(
    pfw,
    columns = vars(survey_acronym),
    threshold = 1
  )
})

test_that("values in `country_code` should match the regular expression: `^[A-Z]{3}$`", {

  expect_col_vals_regex(
    pfw,
    columns = vars(country_code),
    regex = "^[A-Z]{3}$",
    threshold = 1
  )
})

test_that("values in `wb_region_code` should match the regular expression: `^[A-Z]{3}$`", {

  expect_col_vals_regex(
    pfw,
    columns = vars(wb_region_code),
    regex = "^[A-Z]{3}$",
    threshold = 1
  )
})

test_that("values in `pcn_region_code` should match the regular expression: `^[A-Z]{3}$`", {

  expect_col_vals_regex(
    pfw,
    columns = vars(pcn_region_code),
    regex = "^[A-Z]{3}$",
    threshold = 1
  )
})

test_that("entirely distinct rows across `country_code, year, survey_acronym`", {

  expect_rows_distinct(
    pfw,
    columns = vars(country_code, year, survey_acronym),
    threshold = 1
  )
})

test_that("values in `welfare_type` should be in the set of `consumption`, `income`", {

  expect_col_vals_in_set(
    pfw,
    columns = vars(welfare_type),
    set = c("consumption", "income"),
    threshold = 1
  )
})

test_that("values in `survey_coverage` should be in the set of `national`, `rural`, `urban`", {

  expect_col_vals_in_set(
    pfw,
    columns = vars(survey_coverage),
    set = c("national", "rural", "urban"),
    threshold = 1
  )
})
################################################################################

# checking pop raw data
# Generated by pointblank

pop <- load_aux("pop", branch = "DEV")

test_that("column `country_code` exists", {

  expect_col_exists(
    pop,
    columns = vars(country_code),
    threshold = 1
  )
})

test_that("column `year` exists", {

  expect_col_exists(
    pop,
    columns = vars(year),
    threshold = 1
  )
})

test_that("column `pop` exists", {

  expect_col_exists(
    pop,
    columns = vars(pop),
    threshold = 1
  )
})

test_that("column `pop_data_level` exists", {

  expect_col_exists(
    pop,
    columns = vars(pop_data_level),
    threshold = 1
  )
})

test_that("column `pop_domain` exists", {

  expect_col_exists(
    pop,
    columns = vars(pop_domain),
    threshold = 1
  )
})

test_that("column `country_code` is of type: character", {

  expect_col_is_character(
    pop,
    columns = vars(country_code),
    threshold = 1
  )
})

test_that("column `pop_data_level` is of type: character", {

  expect_col_is_character(
    pop,
    columns = vars(pop_data_level),
    threshold = 1
  )
})

test_that("column `pop_domain` is of type: character", {

  expect_col_is_character(
    pop,
    columns = vars(pop_domain),
    threshold = 1
  )
})

test_that("column `year` is of type: numeric", {

  expect_col_is_numeric(
    pop,
    columns = vars(year),
    threshold = 1
  )
})

test_that("column `pop` is of type: numeric", {

  expect_col_is_numeric(
    pop,
    columns = vars(pop),
    threshold = 1
  )
})

test_that("all values in `country_code` should not be NULL", {

  expect_col_vals_not_null(
    pop,
    columns = vars(country_code),
    threshold = 1
  )
})

test_that("all values in `year` should not be NULL", {

  expect_col_vals_not_null(
    pop,
    columns = vars(year),
    threshold = 1
  )
})

test_that("all values in `pop_data_level` should not be NULL", {

  expect_col_vals_not_null(
    pop,
    columns = vars(pop_data_level),
    threshold = 1
  )
})

test_that("values in `country_code` should match the regular expression: `^[A-Z]{3}$`", {

  expect_col_vals_regex(
    pop,
    columns = vars(country_code),
    regex = "^[A-Z]{3}$",
    threshold = 1
  )
})

test_that("entirely distinct rows across `country_code, year, pop_data_level`", {

  expect_rows_distinct(
    pop,
    columns = vars(country_code, year, pop_data_level),
    threshold = 1
  )
})

test_that("values in `pop_domain` should be in the set of `national`, `urban/rural`", {

  expect_col_vals_in_set(
    pop,
    columns = vars(pop_domain),
    set = c("national", "urban/rural"),
    threshold = 1
  )
})

test_that("values in `pop_data_level` should be in the set of `national`, `rural`, `urban`", {

  expect_col_vals_in_set(
    pop,
    columns = vars(pop_data_level),
    set = c("national", "rural", "urban"),
    threshold = 1
  )
})
################################################################################

# checking ppp raw data
# Generated by pointblank

ppp <- load_aux("ppp", branch = "DEV")

test_that("column `country_code` exists", {

  expect_col_exists(
    ppp,
    columns = vars(country_code),
    threshold = 1
  )
})

test_that("column `ppp_year` exists", {

  expect_col_exists(
    ppp,
    columns = vars(ppp_year),
    threshold = 1
  )
})

test_that("column `release_version` exists", {

  expect_col_exists(
    ppp,
    columns = vars(release_version),
    threshold = 1
  )
})

test_that("column `adaptation_version` exists", {

  expect_col_exists(
    ppp,
    columns = vars(adaptation_version),
    threshold = 1
  )
})

test_that("column `ppp` exists", {

  expect_col_exists(
    ppp,
    columns = vars(ppp),
    threshold = 1
  )
})

test_that("column `ppp_default` exists", {

  expect_col_exists(
    ppp,
    columns = vars(ppp_default),
    threshold = 1
  )
})

test_that("column `ppp_default_by_year` exists", {

  expect_col_exists(
    ppp,
    columns = vars(ppp_default_by_year),
    threshold = 1
  )
})

test_that("column `ppp_domain` exists", {

  expect_col_exists(
    ppp,
    columns = vars(ppp_domain),
    threshold = 1
  )
})

test_that("column `ppp_data_level` exists", {

  expect_col_exists(
    ppp,
    columns = vars(ppp_data_level),
    threshold = 1
  )
})

test_that("column `country_code` is of type: character", {

  expect_col_is_character(
    ppp,
    columns = vars(country_code),
    threshold = 1
  )
})

test_that("column `release_version` is of type: character", {

  expect_col_is_character(
    ppp,
    columns = vars(release_version),
    threshold = 1
  )
})

test_that("column `adaptation_version` is of type: character", {

  expect_col_is_character(
    ppp,
    columns = vars(adaptation_version),
    threshold = 1
  )
})

test_that("column `ppp_data_level` is of type: character", {

  expect_col_is_character(
    ppp,
    columns = vars(ppp_data_level),
    threshold = 1
  )
})

test_that("column `ppp_domain` is of type: character", {

  expect_col_is_character(
    ppp,
    columns = vars(ppp_domain),
    threshold = 1
  )
})

test_that("column `ppp_year` is of type: numeric", {

  expect_col_is_numeric(
    ppp,
    columns = vars(ppp_year),
    threshold = 1
  )
})

test_that("column `ppp` is of type: numeric", {

  expect_col_is_numeric(
    ppp,
    columns = vars(ppp),
    threshold = 1
  )
})

test_that("column `ppp_default` is of type: logical", {

  expect_col_is_logical(
    ppp,
    columns = vars(ppp_default),
    threshold = 1
  )
})

test_that("column `ppp_default_by_year` is of type: logical", {

  expect_col_is_logical(
    ppp,
    columns = vars(ppp_default_by_year),
    threshold = 1
  )
})

test_that("all values in `country_code` should not be NULL", {

  expect_col_vals_not_null(
    ppp,
    columns = vars(country_code),
    threshold = 1
  )
})

test_that("all values in `ppp_year` should not be NULL", {

  expect_col_vals_not_null(
    ppp,
    columns = vars(ppp_year),
    threshold = 1
  )
})

test_that("all values in `release_version` should not be NULL", {

  expect_col_vals_not_null(
    ppp,
    columns = vars(release_version),
    threshold = 1
  )
})

test_that("all values in `adaptation_version` should not be NULL", {

  expect_col_vals_not_null(
    ppp,
    columns = vars(adaptation_version),
    threshold = 1
  )
})

test_that("all values in `ppp_data_level` should not be NULL", {

  expect_col_vals_not_null(
    ppp,
    columns = vars(ppp_data_level),
    threshold = 1
  )
})

test_that("values in `country_code` should match the regular expression: `^[A-Z]{3}$`", {

  expect_col_vals_regex(
    ppp,
    columns = vars(country_code),
    regex = "^[A-Z]{3}$",
    threshold = 1
  )
})

test_that("entirely distinct rows across `country_code, ppp_year, release_version, adaptation_version, ppp_data_level`", {

  expect_rows_distinct(
    ppp,
    columns = vars(country_code, ppp_year, release_version, adaptation_version, ppp_data_level),
    threshold = 1
  )
})

test_that("values in `ppp_data_level` should be in the set of `national`, `rural`, `urban`", {

  expect_col_vals_in_set(
    ppp,
    columns = vars(ppp_data_level),
    set = c("national", "rural", "urban"),
    threshold = 1
  )
})

################################################################################

# checking weo raw data
# Generated by pointblank

weo <- load_aux("weo", branch = "DEV")

test_that("column `country_code` exists", {

  expect_col_exists(
    weo,
    columns = vars(country_code),
    threshold = 1
  )
})

test_that("column `year` exists", {

  expect_col_exists(
    weo,
    columns = vars(year),
    threshold = 1
  )
})

test_that("column `weo_gdp` exists", {

  expect_col_exists(
    weo,
    columns = vars(weo_gdp),
    threshold = 1
  )
})

test_that("column `country_code` is of type: character", {

  expect_col_is_character(
    weo,
    columns = vars(country_code),
    threshold = 1
  )
})

test_that("column `year` is of type: numeric", {

  expect_col_is_numeric(
    weo,
    columns = vars(year),
    threshold = 1
  )
})

test_that("column `weo_gdp` is of type: numeric", {

  expect_col_is_numeric(
    weo,
    columns = vars(weo_gdp),
    threshold = 1
  )
})

test_that("all values in `country_code` should not be NULL", {

  expect_col_vals_not_null(
    weo,
    columns = vars(country_code),
    threshold = 1
  )
})

test_that("all values in `year` should not be NULL", {

  expect_col_vals_not_null(
    weo,
    columns = vars(year),
    threshold = 1
  )
})

test_that("values in `country_code` should match the regular expression: `^[A-Z]{3}$`", {

  expect_col_vals_regex(
    weo,
    columns = vars(country_code),
    regex = "^[A-Z]{3}$",
    threshold = 1
  )
})

test_that("entirely distinct rows across `country_code, year`", {

  expect_rows_distinct(
    weo,
    columns = vars(country_code, year),
    threshold = 1
  )
})
################################################################################
